### ISSUE TITLE
Wrong reference to token in Module?

### ISSUE THREAD

**Issue by weq** [pkelly808/Terraform#1]
Steps to reproduce:
On clean machine,
```ps1
install-module terraform
import-module terraform
set-terraform -Server app.terraform.io -Token <appToken> -Org <orgName>
Get-TFWorkspace | ? name -like CF-* | Remove-TFWorkspace
```
Gives you the follow error:
```
WARNING: Missing Token for vault_token key, use Get-CNVToken
Where-Object: The 'Ilike' operator failed: System error..
```
https://github.com/pkelly808/Terraform/blob/09903c4d6b38461dec1aac3515f9b9f9c30ed594/TFWorkspace.ps1#L468`
I can't exactly tell what this line is supposed to solve or is it perhaps something that should've been deleted at some point?

**Comment by pkelly808** [comment]
Hi @weq, you need a token to connect to the TF API, please take a look at the readme file:
https://github.com/pkelly808/Terraform/tree/09903c4d6b38461dec1aac3515f9b9f9c30ed594#connect-to-terraform-api

Let me know if you have any other questions or issues.

**Comment by weq** [comment]
The error you throw referes to a function called `Get-CNVToken` in your module and I did specify a TF API token as stated by my example I just censored it.
